language: Swift
osx_image: xcode9.1
branches:
  only:
    - master
env:
  - ACTION=test  PLATFORM=iOS     DESTINATION='platform=iOS Simulator,name=iPhone 8'
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet  
  - carthage bootstrap --platform iOS
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  - xcodebuild -workspace QuickSwift.xcworkspace -scheme QuickSwift -destination "$DESTINATION" $ACTION | xcprettys

