language: Swift
osx_image: xcode9.1
branches:
  only:
    - master
env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 8'
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet  
before_script:
  - cd QuickSwift;carthage bootstrap --platform iOS
  - cd ..
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace QuickSwift.xcworkspace -scheme QuickSwift -destination "$DESTINATION" test | xcpretty

